### ISSUE TITLE
Validators

### ISSUE THREAD

**Issue by jonmchan** [berkshelf/semverse#6]
It would be great if we can have an ActiveModel::Validator for semver and semver constraint. I'll try to put together a PR.

**Comment by jonmchan** [comment]
I just realized that this project is a straight ruby project without depedencies on rails. Would it be bad to introduce the ActiveModel gem to this project? Is there any way to make it optional?

**Comment by sethvargo** [comment]
@jonmchan is there a particular reason you need validators? Why not just write one inside your Rails app? I think it might be out of scope since this isn't a Rails-specific gem.

**Comment by jonmchan** [comment]
I was thinking it would be beneficial for semverse to define a validator at the model level so that invalid semver strings would be caught without exceptions being thrown when the fields are converted into ```Semverse::Version```. It is problematic when regex validation is written for semver because it may allow more or less than what Semverse supports. 

The Semverse::Version.split is a good standard for validation, and I can just make my own validator within my app that calls that, but I believe that having an official validator will be better as it would encourage developers to use this methodology instead of naively implementing bad regex for validation.

**Comment by sethvargo** [comment]
@jonmchan if you believe this functionality would benefit the Rails community, I would recommend creating your own gem (maybe active-model-semver) that depends on this gem and active model and includes the custom validator you have mentioned. This is not something we will be adding to semverse core, however :smile:.
